"""Table Clt Habit User

Revision ID: 53844702c72c
Revises: 
Create Date: 2020-06-19 19:02:55.208420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53844702c72c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numHabit', sa.Integer(), nullable=True),
    sa.Column('tipoHabit', sa.String(length=25), nullable=True),
    sa.Column('capXHabit', sa.Integer(), nullable=True),
    sa.Column('costoXHabit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habitaciones_numHabit'), 'habitaciones', ['numHabit'], unique=False)
    op.create_index(op.f('ix_habitaciones_tipoHabit'), 'habitaciones', ['tipoHabit'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameClt', sa.String(length=50), nullable=True),
    sa.Column('apellidoPateClt', sa.String(length=50), nullable=True),
    sa.Column('apellidoMateClt', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('phone2', sa.String(length=12), nullable=True),
    sa.Column('placaCarro', sa.String(length=16), nullable=True),
    sa.Column('placaCarro2', sa.String(length=16), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_apellidoMateClt'), 'clientes', ['apellidoMateClt'], unique=False)
    op.create_index(op.f('ix_clientes_apellidoPateClt'), 'clientes', ['apellidoPateClt'], unique=False)
    op.create_index(op.f('ix_clientes_nameClt'), 'clientes', ['nameClt'], unique=False)
    op.create_table('rentaHabitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fkIdHabitacion', sa.Integer(), nullable=True),
    sa.Column('fkIdClientes', sa.Integer(), nullable=True),
    sa.Column('importeTotal', sa.Integer(), nullable=True),
    sa.Column('numPersonas', sa.Integer(), nullable=True),
    sa.Column('diaInicio', sa.DateTime(), nullable=True),
    sa.Column('diaFinalizado', sa.DateTime(), nullable=True),
    sa.Column('diasDeEstancia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fkIdClientes'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['fkIdHabitacion'], ['habitaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentaHabitaciones_diaFinalizado'), 'rentaHabitaciones', ['diaFinalizado'], unique=False)
    op.create_index(op.f('ix_rentaHabitaciones_diaInicio'), 'rentaHabitaciones', ['diaInicio'], unique=False)
    op.create_index(op.f('ix_rentaHabitaciones_fkIdClientes'), 'rentaHabitaciones', ['fkIdClientes'], unique=False)
    op.create_index(op.f('ix_rentaHabitaciones_fkIdHabitacion'), 'rentaHabitaciones', ['fkIdHabitacion'], unique=False)
    op.create_index(op.f('ix_rentaHabitaciones_importeTotal'), 'rentaHabitaciones', ['importeTotal'], unique=False)
    op.create_index(op.f('ix_rentaHabitaciones_numPersonas'), 'rentaHabitaciones', ['numPersonas'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentaHabitaciones_numPersonas'), table_name='rentaHabitaciones')
    op.drop_index(op.f('ix_rentaHabitaciones_importeTotal'), table_name='rentaHabitaciones')
    op.drop_index(op.f('ix_rentaHabitaciones_fkIdHabitacion'), table_name='rentaHabitaciones')
    op.drop_index(op.f('ix_rentaHabitaciones_fkIdClientes'), table_name='rentaHabitaciones')
    op.drop_index(op.f('ix_rentaHabitaciones_diaInicio'), table_name='rentaHabitaciones')
    op.drop_index(op.f('ix_rentaHabitaciones_diaFinalizado'), table_name='rentaHabitaciones')
    op.drop_table('rentaHabitaciones')
    op.drop_index(op.f('ix_clientes_nameClt'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_apellidoPateClt'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_apellidoMateClt'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_habitaciones_tipoHabit'), table_name='habitaciones')
    op.drop_index(op.f('ix_habitaciones_numHabit'), table_name='habitaciones')
    op.drop_table('habitaciones')
    # ### end Alembic commands ###
